# Simple server configuration example
server:
  name: simple-mcp
  desc: A simple MCP server with basic tools
  version: "1.0.0"

tools:
  HelloWorld:
    cmd: echo "Hello, {{ name }}!"
    desc: Say hello to someone
    args:
      - name: name
        help: Name to greet
        default: "World"

  CurrentTime:
    cmd: date
    desc: Get current date and time
    help-cmd: date --help